# Site settings
title: What title?
email: songjiapei@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What description?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jack-song.com" # the base hostname & protocol for your site
github_username:  jack-song

# Build settings
markdown: kramdown

defaults:
    scope:
        path: ""
        type: ""
    values:
        layout: ""
