# Site settings
title: Jack Song
email: jackthesong@gmail.com
description: Comments on various software and personal projects
url: "http://www.jack-song.me" # the base hostname & protocol for your site
github_username: jack-song
permalink: none

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

sass:
  sass_dir: _sass
