# Site settings
title: Jack Song
email: jackthesong@gmail.com
description: Comments on various software and personal projects
baseurl: "" # the subpath of your site, e.g. /blog/ (not planning to use)
url: "http://www.jack-song.me" # the base hostname & protocol for your site
github_username:  jack-song
permalink: none

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass

defaults:
    scope:
        path: ""
        type: ""
    values:
        layout: ""
